apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: botkube-helm-values
  namespace: monitoring
spec:
  keys:
    - values.yaml
  path: secret/deployments/monitoring/botkube/botkube-helm-values
  type: Opaque
