---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: botkube
  rollback:
    enable: true
  chart:
    repository: https://infracloudio.github.io/charts
    name: botkube
    version: v0.11.0
  values:
    image:
      repository: mwillemsma/botkube-arm
      tag: v0.11.0
    serviceMonitor:
      enabled: true
    config:
      settings:
        clustername: k3s
        configwatcher: true
        upgradeNotifier: true
      resources:
        - name: pod
          namespaces:
            include:
              - all
          events:
            - all

  valueFileSecrets:
  - name: "botkube-helm-values"
